name: CI
on:
  push:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
  #environment
env:
  MONGO_URL: ${{secrets.MONGO_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4']

    concurrency: test_environment
    env:
      MONGO_URL: ${{secrets.MONGO_URL}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name:  Setup nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: '14.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 12345
      - name: install dependecies
        run: npm install

      - name: Run the tests
        run: npm run test
        env: 
          CI: true